### ISSUE TITLE
Crash with `NoSuchMethodError ... shouldExecute(...)` after upgrading

### ISSUE THREAD

**Issue by JAWS-tm** [JetBrains/compose-hot-reload#375]
**Describe the bug**

After updating to 1.0.0-beta07, I can no longer start the project with `hotRunDesktop`. The app crashes immediately with a `NoSuchMethodError`.

```kotlin
  ________________________________________________________________________________________________
| 
| Compose Hot Reload (1.0.0-beta07)
| Running 'com.playmoweb.kimai.MainKt'
| JetBrains Runtime: /Users/jules/.gradle/jdks/jetbrains_s_r_o_-21-aarch64-os_x.2/jbrsdk_jcef-21.0.8-osx-aarch64-b895.146/Contents/Home/bin/java
| ________________________________________________________________________________________________
| Explicit Reload Mode:
| Use `./gradlew reload` to hot reload the application
| Use `./gradlew :composeApp:hotReloadDesktopMain` to hot reload the application (alternative)
| Use `./gradlew :composeApp:hotRunDesktop --auto` to automatically reload the application on source changes
| ________________________________________________________________________________________________

Exception in thread "main" java.lang.NoSuchMethodError: 'boolean androidx.compose.runtime.Composer.shouldExecute(boolean, int)'
	at org.jetbrains.compose.reload.jvm.JvmDevelopmentEntryPoint.setContent$lambda$18(DevelopmentEntryPoint.kt)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33)
	at androidx.compose.ui.awt.ComposeDialog$setContent$6.invoke(ComposeDialog.desktop.kt:217)
	at androidx.compose.ui.awt.ComposeDialog$setContent$6.invoke(ComposeDialog.desktop.kt:216)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107)
```

**To Reproduce**

I don't have any idea of what I did wrong actually.

**Expected behavior**

The application should start and hot reload should work as before.

**Environment**
 - OS: MacOS
 - Kotlin version: `2.1.20`
 - Compose Multiplatform version: `1.7.3`
 - Compose Hot Reload version: `1.0.0-beta07`

**Comment by sellmair** [comment]
Thank you for the report; As far as I can tell our minimum supported CMP version is 1.8.2. 
Would you mind upgrading to this version and checking if the issue still persists?
We could potentially start testing against 1.7.3 and bringing compliance for it as well, if we see big enough usage

**Comment by JAWS-tm** [comment]
Okay, I wasn’t aware of this requirement. It would be helpful to mention it in the README so others don’t run into the same issue.
Thanks

**Comment by sellmair** [comment]
Good point! I added it to the readme. 
If you can't upgrade to 1.8.2 then I can share a Gradle property with you that might get you working again 👍

**Comment by JAWS-tm** [comment]
Perfect, thanks 👌  
That’s fine, I reverted to `alpha05` for now, but I’ll bump my versions soon

**Comment by sellmair** [comment]
Oh, any reasons why not using beta06 or beta05. Dropping to alpha05 seems quite drastic?

**Comment by JAWS-tm** [comment]
No particular reason, it’s just the version I started my project with. I’ll bump this soon

**Comment by sellmair** [comment]
I'd close the ticket for now, if you experience any issues like this, please just re-open and we will investigate it asap!
